### ISSUE TITLE
Code for Tables 4 & 5 results.

### ISSUE THREAD

**Issue by edsonroteia** [samyak0210/AViNet#1]
Hi, I am having trouble identifying the steps necessary reproduce the results (AViNet only) for tables 4 & 5 in your Arxiv document. I was able to get extract the maps like the README.md describes, could not find the code to generate the metrics using those maps.

```
Datasets: DIEM, Coutrot1, Coutrot2, AVAD, ETMD, SumMe.
Metrics: CC, sAUC, AUC, NSS, SIM.
```

Could you please provide the steps necessary to replicate such experiments?

Thanks in advance!

**Comment by samyak0210** [comment]
Hi,

You can use the file eval_diem.m to calculate the metrics on the generated maps
